# Generated by Django 5.1.4 on 2025-02-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_alter_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_name',
        ),
    ]
