# Generated by Django 5.1.4 on 2025-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default='User Name', max_length=30, verbose_name='User Name'),
        ),
    ]
