# Generated by Django 5.1.4 on 2025-02-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default='', max_length=30, verbose_name='User Name'),
        ),
    ]
