# Generated by Django 5.1.4 on 2025-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.CharField(default='default', max_length=30, verbose_name='User Name'),
        ),
    ]
