# Generated by Django 5.1.4 on 2025-02-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_alter_feedback_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='author_id',
        ),
    ]
