# Generated by Django 5.1.4 on 2025-02-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_rename_author_feedback_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author_id',
            new_name='author',
        ),
    ]
