# Generated by Django 5.1.4 on 2025-02-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_rename_author_id_feedback_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='author_name',
            field=models.CharField(default='default_author_name'),
        ),
    ]
