# Generated by Django 5.1.4 on 2025-04-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tags_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(related_name='vacancies', to='main.tags', verbose_name='Теги'),
        ),
    ]
