# Generated by Django 5.1.4 on 2025-06-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vacancy_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
