# Generated by Django 5.1.4 on 2025-02-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedbacks',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
