# Generated by Django 5.1.4 on 2025-03-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_feedbacks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="feedbacks",
        ),
    ]
